<a href="https://colab.research.google.com/github/Swapn2/deep_learning/blob/main/Backpropogation_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import pandas as pd

In [50]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6,],[5,12,7]],columns=['cgpa','Profile_score','lpa'])
df.head()

cgpa  Profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [51]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1,L):
    parameters['W' + str(l)] = np.ones((layer_dims[l-1],layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l],1))
  return parameters

In [52]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [53]:
def linear_forward(A_prev,W,b):
  Z = np.dot(W.T,A_prev) + b
  # cache = (A_prev,W,b)
  return Z

In [54]:
def L_layer_forward(X,parameters):
  A = X
  L = len(parameters)//2
  for l in range(1,L+1):
    A_prev = A
    w1 = parameters['W' + str(l)]
    b1 = parameters['b' + str(l)]
    print("A"+str(l-1)+":",A_prev)
    print("W"+str(l)+":",w1)
    print("b"+str(l)+":",b1)
    print("--"*20)
    A = linear_forward(A_prev,w1,b1)
    print("A"+str(l)+":",A)
    print("**"*20)
  return A,A_prev

In [55]:
x = df[['cgpa','Profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]



parameters = initialize_parameters([2,2,1])
L_layer_forward(x,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************


(array([[0.32]]),
 array([[1.6],
        [1.6]]))

In [56]:
(y-.32)**2

13.5424

In [57]:
y_hat = y_hat[0][0]

In [58]:
def update_parameters(parameters,y,y_hat,A1,x):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0])

In [59]:
x = df[['cgpa','Profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)

A0: [[8]
 [8]]
W1: [[0.1 0.1]
 [0.1 0.1]]
b1: [[0.]
 [0.]]
----------------------------------------
A1: [[1.6]
 [1.6]]
****************************************
A1: [[1.6]
 [1.6]]
W2: [[0.1]
 [0.1]]
b2: [[0.]]
----------------------------------------
A2: [[0.32]]
****************************************


In [60]:
y_hat = y_hat[0][0]

In [61]:
A1

array([[1.6],
       [1.6]])

In [62]:
update_parameters(parameters,y , y_hat,A1,x)

In [63]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [64]:
x = df[['cgpa','Profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]

# parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)

A0: [[7]
 [9]]
W1: [[0.10658137 0.10658137]
 [0.10658137 0.10658137]]
b1: [[0.00082267]
 [0.00082267]]
----------------------------------------
A1: [[1.70612461]
 [1.70612461]]
****************************************
A1: [[1.70612461]
 [1.70612461]]
W2: [[0.111776]
 [0.111776]]
b2: [[0.119136]]
----------------------------------------
A2: [[0.50054357]]
****************************************


In [65]:
def update_parameters(parameters,y,y_hat,A1,x):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0])

In [66]:
update_parameters(parameters,y , y_hat,A1,x)

<ipython-input-65-5594bbb24aaf>:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-65-5594bbb24aaf>:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-65-5594bbb24aaf>:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 *

In [67]:
parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [68]:
x = df[['cgpa','Profile_score']].values[2].reshape(2,1)
y = df[['lpa']].values[2][0]

# parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)


def update_parameters(parameters,y,y_hat,A1,x):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0])

update_parameters(parameters,y , y_hat,A1,x)


parameters


A0: [[ 6]
 [10]]
W1: [[0.11458955 0.1168776 ]
 [0.11458955 0.1168776 ]]
b1: [[0.0019667]
 [0.0019667]]
----------------------------------------
A1: [[1.83539945]
 [1.87200826]]
****************************************
A1: [[1.83539945]
 [1.87200826]]
W2: [[0.12712927]
 [0.12712927]]
b2: [[0.13612818]]
----------------------------------------
A2: [[0.6074482]]
****************************************


<ipython-input-68-2903d0d75fa7>:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-68-2903d0d75fa7>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-68-2903d0d75fa7>:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

{'W1': array([[0.12409711, 0.13272353],
        [0.12409711, 0.13272353]]),
 'b1': array([[0.00355129],
        [0.00355129]]),
 'W2': array([[0.14692424],
        [0.14692424]]),
 'b2': array([[0.15770934]])}

In [48]:
x = df[['cgpa','Profile_score']].values[3].reshape(2,1)
y = df[['lpa']].values[3][0]

# parameters = initialize_parameters([2,2,1])
y_hat,A1 = L_layer_forward(x,parameters)


def update_parameters(parameters,y,y_hat,A1,x):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0]*x[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0]*x[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y- y_hat)*parameters['W2'][1][0])

update_parameters(parameters,y , y_hat,A1,x)


parameters


A0: [[ 5]
 [12]]
W1: [[0.15745817 0.16531736]
 [0.15745817 0.16531736]]
b1: [[0.00767347]
 [0.00767347]]
----------------------------------------
A1: [[2.6844624 ]
 [2.81806864]]
****************************************
A1: [[2.6844624 ]
 [2.81806864]]
W2: [[0.19619389]
 [0.19619389]]
b2: [[0.20620846]]
----------------------------------------
A2: [[1.28577144]]
****************************************


<ipython-input-48-d54acd11799e>:9: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-48-d54acd11799e>:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y- y_hat)*A1[0][0])
<ipython-input-48-d54acd11799e>:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001

{'W1': array([[0.17042222, 0.19643108],
        [0.17042222, 0.19643108]]),
 'b1': array([[0.01026628],
        [0.01026628]]),
 'W2': array([[0.22687315],
        [0.22687315]]),
 'b2': array([[0.23830161]])}