<a href="https://colab.research.google.com/github/Swapn2/deep_learning/blob/main/backpropogation_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6,],[5,12,7]],columns=['cgpa','Profile_score','lpa'])
df.head()

cgpa  Profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense


In [4]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()

[array([[-0.42841005, -0.8874768 ],
        [ 0.57241344,  0.14047074]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.7870287],
        [ 0.5390096]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
new_weights = [np.array([[.1,.1],
                         [.1,.1]],dtype=np.float32),
np.array([0,0],dtype=np.float32),
np.array([[0.1],
          [.1]], dtype = np.float32),
np.array([0],dtype=np.float32)]


model.set_weights(new_weights)

In [11]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 0s 3ms/step - loss: 27.8902
Epoch 2/75
4/4 [==============================] - 0s 3ms/step - loss: 27.5740
Epoch 3/75
4/4 [==============================] - 0s 2ms/step - loss: 27.2620
Epoch 4/75
4/4 [==============================] - 0s 2ms/step - loss: 26.8945
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 26.5455
Epoch 6/75
4/4 [==============================] - 0s 2ms/step - loss: 26.1932
Epoch 7/75
4/4 [==============================] - 0s 2ms/step - loss: 25.8388
Epoch 8/75
4/4 [==============================] - 0s 2ms/step - loss: 25.4423
Epoch 9/75
4/4 [==============================] - 0s 2ms/step - loss: 25.0469
Epoch 10/75
4/4 [==============================] - 0s 2ms/step - loss: 24.6437
Epoch 11/75
4/4 [==============================] - 0s 2ms/step - loss: 24.2624
Epoch 12/75
4/4 [==============================] - 0s 2ms/step - loss: 23.8306
Epoch 13/75
4/4 [==============================] - 0s 2ms/ste

In [14]:
model.get_weights()

[array([[0.37382275, 0.37382275],
        [0.36590326, 0.36590326]], dtype=float32),
 array([0.2725555, 0.2725555], dtype=float32),
 array([[0.3731763],
        [0.3731763]], dtype=float32),
 array([0.20493904], dtype=float32)]